language: node_js
node_js:
  - "8"
before_install:
  - npm install
  - chmod +x deploy.sh
branches:
  only:
    - master
stages:
  # - lint
  - build
  - deploy
jobs:
  include:
    # - stage: lint
    #   script:
    #     - npm run lint
    - stage: build
      script:
        - npm run docs:build
    - stage: deploy
      script:
        - cd ~ && source ./deploy.sh
