language: node_js
node_js:
  - "8"
# before_install:
#   - npm install vuepress -g
branches:
  only:
    - master
stages:
  # - lint
  - build
  - deploy
jobs:
  include:
    # - stage: lint
    #   script:
    #     - npm run lint
    - stage: build
      script:
        - npm run docs:build
    - stage: deploy
      script:
        - ./deploy.sh
